server:
  port:8081

spring:
  datasource:
    url: jdbc:h2:file:ledpanelapidb01;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true