server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./ledpanelapidb01;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
